# Generated by Django 2.2 on 2019-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='future_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='future_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
