# Generated by Django 3.0.14 on 2023-02-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalog', '0002_auto_20190418_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controller',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['id']},
        ),
    ]
